### ISSUE TITLE
Doesn't seem to re-transpile app/main.ts, associated with renderer process (should be main)

### ISSUE THREAD

**Issue by subatomicglue** [catdad/electronmon#65]
I run:
```
ng serve -c web -o
```

and then:
```
wait-on tcp:4200 && tsc -p tsconfig.serve.json && npx electronmon . --serve
```

When I re-save `./app/main.ts`, I see `electronmon` spit out:
```
[electronmon] renderer file change: app/main.ts
```
ok...    but that's a `main` file, not a `renderer` file... and....    it didn't transpile.  It didn't even re-run the main process, It reloaded the renderer only.    So, I can't make an edit and hit save, and see it, unless I ctrl-C out of `electronmon` and totally restart, then it's fine.

-> It seems that `electronmon` is (incorrectly) associating `main.ts` with the `renderer` process, instead of the `main` process.

How do I fix this?   The `README.md` gives `patterns` and some advice to ignore files, but doesn't tell me how to use that in the situation when `electronmon` is incorrectly associating the files with the wrong `main` vs `renderer` process.

saving `package.json` works:
```
[electronmon] main file change: package.json
will quit
[electronmon] restarting app due to file change
```
and trying to add a pattern to `package.json` doesn't make any changes (the main.ts does not rerun)
```
  "electronmon": {
    "patterns": ["app/**"]
  },
```
it just gives the same `renderer` line when saving `main.ts`
```
[electronmon] renderer file change: app/main.ts
```

**Comment by subatomicglue** [comment]
Well, I figured out that maybe I should add the `--watch` to the `tsc` command above:
```
wait-on tcp:4200 && tsc --watch -p tsconfig.serve.json && npx electronmon . --serve
```

which blocks, and `electronmon` never runs...
so I run in 2 separate terminals as a test:

Terminal 1
```
wait-on tcp:4200 && tsc --watch -p tsconfig.serve.json
```
Terminal 2
```
npx electronmon . --serve
```

It runs...   But when I save `app/main.ts` I get another electron app running.   
Save it 3 times, I get 3 more apps....

Ideas?

**Comment by catdad** [comment]
I think there are two issues here:

First, when you use a compile-to-javascript language, the source code (in your case the typescript files) is not what is run by Electron. Electron can only run JavaScript files. `ng` takes your source typescript and creates output JavaScript, which is then what Electron uses. When electronmon comes into play, it works the same way. It can only analyze code (that is, the JavaScript files output by your build), and makes the assumption that all the other files are "miscellaneous renderer files" that it just doesn't know how to analyze. Again, the only actual code that is run in your case is the output JavaScript files from the build. Typescript files cannot and are not run as code. You can ignore those (as well as sourcemaps) using the `patterns` property you mentioned.

Second, multiple apps... since there are no repro steps provided, I can only take guesses here. Electronmon sends standard kill signals to kill the app when restarting it. However, like any other signal, Electron can overload it and choose not to exit. My guess is that is what might be happening, but again, I have no way of knowing if there is no way for me to easily and simply reproduce this problem.

**Comment by subatomicglue** [comment]
Found it!

```
if (serve) {
    win.webContents.openDevTools();
    require('electron-reload')(__dirname, {
      electron: require(path.join(__dirname, '/../node_modules/electron' ))
    });
    win.loadURL('http://localhost:4200');
  }
```

This was in my `app/main.ts` from the project I copied this from (angular + electron example I found online).

So, in the end - my app WAS exiting, but then 2 were launching.   One from `electron-reload` and one from `electronmon`. 
All is good now.

**Comment by omardevelopsGit** [comment]
I have almost the same problem

But am not using typescript, the same exact problem, when changing main.js file, it considers it as renderer file, and also package.json is considered as renderer file.

Note: package.json "main" path is pointing to "main.js" file
